export const VendorConstant = {

    
  
    VENDOR_TABLE_SAGA: "VENDOR_TABLE_SAGA",
    VENDOR_TABLE_REQUEST: "VENDOR_TABLE_REQUEST",
    VENDOR_TABLE_RESPONSE: "VENDOR_TABLE_RESPONSE",
    VENDOR_TABLE_API: "/vendors",
};