export const ChargingStationConstant = {

    CHARGING_STATION_SAGA: "CHARGING_STATION_SAGA",
    CHARGING_STATION_REQUEST: "CHARGING_STATION_REQUEST",
    CHARGING_STATION_RESPONSE: "CHARGING_STATION_RESPONSE",
    CHARGING_STATION_API: "/charging-stations",



    CHARGING_STATION_DETAIL_SAGA: "CHARGING_STATION_DETAIL_SAGA",
    CHARGING_STATION_DETAIL_REQUEST: "CHARGING_STATION_DETAIL_REQUEST",
    CHARGING_STATION_DETAIL_RESPONSE: "CHARGING_STATION_DETAIL_RESPONSE",
    CHARGING_STATION_DETAIL_API: "/charging-station/dealer/:id",



    ADD_CHARGING_POINT_API: "/charging-point",

    ADD_CHARGING_CONNECTOR_API: "/charging-point/add-connector",
    
    EDIT_CHARGING_POINT_API: "/charging-point",

    EDIT_CHARGING_CONNECTOR_API: "/charging-point/update-connector",
    



    CHARGING_STATION_DELETE_SAGA: "CHARGING_STATION_DELETE_SAGA",
    CHARGING_STATION_DELETE_REQUEST: "CHARGING_STATION_DELETE_REQUEST",
    CHARGING_STATION_DELETE_RESPONSE: "CHARGING_STATION_DELETE_RESPONSE",
    CHARGING_STATION_DELETE_API: "/charging-station/:id",


    GET_CHARGING_POINT_API: "/charging-points",
    GET_CHARGING_POINT_REQUEST: "GET_CHARGING_POINT_REQUEST",
    GET_CHARGING_POINT_RESPONSE: "GET_CHARGING_POINT_RESPONSE",
    GET_CHARGING_POINT_SAGA: "GET_CHARGING_POINT_SAGA",

    DELETE_CHARGING_CONNECTOR_API: "/charging-point/delete-connector/:id",
    DELETE_CHARGING_CONNECTOR_REQUEST: "DELETE_CHARGING_CONNECTOR_REQUEST",
    DELETE_CHARGING_CONNECTOR_RESPONSE: "DELETE_CHARGING_CONNECTOR_RESPONSE",
    DELETE_CHARGING_CONNECTOR_SAGA: "DELETE_CHARGING_CONNECTOR_SAGA",





};